---
# This file contains the configuration for golangci-lint.
# See https://golangci-lint.run/usage/configuration/ for reference.

version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - exhaustive
    - nonamedreturns
    - predeclared
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: cli.CreateProcessorLegacy'
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.DB).Close
        - fmt.Fprintf
        - fmt.Fprintln

formatters:
  enable:
    - gofmt
